# Generated by Django 5.0.4 on 2024-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10, verbose_name='Date')),
                ('amt', models.FloatField(max_length=9, verbose_name='Amount')),
                ('cat', models.CharField(max_length=15, verbose_name='Category')),
                ('ven', models.CharField(max_length=20, verbose_name='Vendor')),
                ('cap', models.CharField(max_length=45, verbose_name='Caption')),
                ('pmeth', models.CharField(max_length=20, verbose_name='Payment Method')),
            ],
        ),
    ]
